Add support for API key authentication
iqm-finland/iqm-client pull request #102
Opened 2023-11-15 13:29 UTC by milankinen

Hello!

This PR proposes an API key support to the `iqm-client`.

In this proposal, API key authentication will use the same bearer token authentication schema as the external access token authentication, so the API key will be passed to the server in the `Authorization` header as a bearer token. Server can identify which type (external access token or api key) the token is and select correct authentication mechanism accordingly.

The implementation tries to follow the existing conventions to pass the key:
1. Prefer direct constructor arguments (`IQMClient(server_url='...', api_key='123')`)
2. Get API key from the `IQM_API_KEY` environment variable

The changes in this PR should be backwards compatible: If API key is not set, access token authentication is used normally so any existing clients should continue working without any modifications. There should not be any changes required from the existing server either: only those servers that want to support API keys can implement the support but it's not required since the client still supports the access token authentication.

2023-11-28 09:41 UTC, olliahonen commented on INTEGRATION_GUIDE.rst
> +Currently there are two possible methods to get an authentication token:
```suggestion
Currently, there are two possible ways of obtaining an authentication token:
```

2023-11-28 09:42 UTC, olliahonen commented on INTEGRATION_GUIDE.rst
> +is the recommended way to generate and refresh tokens.IQM client can use these tokens by
```suggestion
is the recommended way to generate and refresh tokens. IQM client can use these tokens by
```

2023-11-28 09:43 UTC, olliahonen commented on INTEGRATION_GUIDE.rst
> +2. Plaintext token obtained from the server dashboard. These tokens have longer lifespan
```suggestion
2. Plaintext token obtained from a server dashboard. These tokens may have a longer lifespan
```

2023-11-28 16:55 UTC, olliahonen commented on INTEGRATION_GUIDE.rst
> +IQM uses Bearer token authentication to manage access to quantum computers.
```suggestion
IQM uses Bearer token authentication to manage access to quantum computers.
Currently, there are two possible ways of providing an authentication token
to IQM client:

1. OAuth 2.0 tokens using `Cortex CLI <https://github.com/iqm-finland/cortex-cli>`_ which
is the recommended way to generate and refresh tokens. IQM client can use these tokens by
reading an environment variable ``IQM_TOKENS_FILE`` pointing to the tokens file managed by
Cortex CLI.

2. Plaintext token obtained from a server dashboard. These tokens may have longer lifespan
than access tokens generated by Cortex CLI, and thus IQM client won't attempt to refresh
them. The generated token is set as the `IQM_TOKEN` environment variable, and IQM client
reads it from there. The recommended usage is to set the environment variable in
`.bashrc`/`.zshrc` so that it's set up automatically for each terminal session.

Note that a server may not support both authentication methods. The supported
authentication methods and their instructions are provided at the server's front page.
```

2023-11-28 16:56 UTC, olliahonen commented on INTEGRATION_GUIDE.rst
> +IQM uses Bearer token authentication to manage access to quantum computers.
Please replace the entire paragraph with this 🙏

2023-11-28 16:57 UTC, olliahonen commented on src/iqm/iqm_client/iqm_client.py
> +            environment variable. If tokens_file (or IQM_TOKENS_FILE) is set, it'll
```suggestion
            environment variable. If tokens_file (or IQM_TOKENS_FILE) is set, it will
```

2023-11-28 16:57 UTC, olliahonen requested changes
See individual comments 👍

2023-12-05 11:31 UTC, kukushechkin commented on tests/test_authentication.py
> +def test_tokens_file_overrides_plaintext_token(base_url):
What is the justification behind cortex-cli having priority over an explicitly provided API token? I guess it is fine either way (only one should be used at a time), but is it just a random decision or there is some logic behind it?

2023-12-05 11:32 UTC, kukushechkin commented
Change log update is necessary.

2023-12-05 12:16 UTC, smite commented on INTEGRATION_GUIDE.rst
> +IQM uses Bearer token authentication to manage access to quantum computers.
```suggestion
IQM uses bearer token authentication to manage access to quantum computers.
```

2023-12-05 12:19 UTC, smite commented on INTEGRATION_GUIDE.rst
> +authentication methods and their instructions are provided at the server's front page.
```suggestion
authentication methods and their instructions are provided on the server's front page.
```

2023-12-07 11:14 UTC, milankinen commented on tests/test_authentication.py
> +def test_tokens_file_overrides_plaintext_token(base_url):
@olliahonen preferred to prioritize tokens file, so he might have some background information?

2023-12-07 13:01 UTC, olliahonen approved these changes
LGTM

2023-12-07 15:50 UTC, merged