Added url validation for starting with http, https
iqm-finland/iqm-client pull request #20
Opened 2022-02-08 17:09 UTC by WingCode

The validation (starting with http, https) is expected by the docstring but not enforced.
It might helpful to fail early and fast since there might be some prior resource intensive steps before utilising the IQM client.

2022-02-10 08:46 UTC, hay-k commented on src/iqm_client/iqm_client.py
> +        if not url.startswith(("http","https")):
```suggestion
        if not url.startswith(("http:", "https:")):
```

2022-02-10 09:02 UTC, hay-k requested changes
You will also need to add a unit test case to cover this new exception. Let me know if you need any help.

2022-02-10 09:03 UTC, hay-k commented
@WingCode Thanks for your pull request. I have reviewed it and requested some changes above.

2022-02-20 12:04 UTC, WingCode reviewed
Addressed review comments. Fix changelog, IQM client, added  tests.

2022-02-22 09:49 UTC, hay-k requested changes

2022-02-22 09:49 UTC, hay-k commented on tests/test_iqm_client.py
> +    assert f"The URL schema has to be http or https. Incorrect schema in URL: {invalid_base_url}" == str(exc.value)
```suggestion
    assert f"The URL schema has to be http or https. Incorrect schema in URL: {invalid_base_url}" == str(exc.value)
    
```

2022-02-22 09:49 UTC, hay-k commented on tests/test_iqm_client.py
> +        assert False, f" IQMClient raised an exception {exc}"
I think you can remove this test, since it is naturally covered by the other tests already.

2022-02-22 11:17 UTC, hay-k approved these changes

2022-02-22 11:18 UTC, merged