Comp 305 publish json schema for iqm circuit execution request
iqm-finland/iqm-client pull request #24
Opened 2022-04-21 14:30 UTC by q-mat-beu

Add capability to publish a json schema of the circuit execution request that is sent to the IQM backend during the docs build step.

2022-04-22 10:12 UTC, smite requested changes

2022-04-22 11:22 UTC, q-mat-beu commented on .github/workflows/ci.yml
> +          fetch-depth: 0
Yes we need the git history for fetching the latest tag.

2022-04-25 11:10 UTC, hay-k commented on docs/generate_json_schemas.py
> +        '$schema': 'https://json-schema.org/draft/2020-12/schema',
Maybe a naive question, but why does this have `draft` in the path?

2022-04-25 11:13 UTC, hay-k commented on docs/generate_json_schemas.py
> +    """Generate a JSON schema dictionary from the given Pydantic model.
The arguments are not documented in the docstring.

2022-04-25 11:14 UTC, hay-k commented on docs/generate_json_schemas.py
> +        '$id': f'https://www.meetiqm.com/iqm_client/{filename}_v{tag}.json',
Is this a valid URL though?

2022-04-25 11:24 UTC, q-mat-beu commented on docs/generate_json_schemas.py
> +        '$schema': 'https://json-schema.org/draft/2020-12/schema',
I think each JSON schema standard is a draft. See here: https://json-schema.org/specification-links.html#2020-12

2022-04-25 12:38 UTC, q-mat-beu commented on docs/generate_json_schemas.py
> +        '$id': f'https://www.meetiqm.com/iqm_client/{filename}_v{tag}.json',
Now it should be.

2022-04-26 10:09 UTC, hay-k approved these changes

2022-04-26 11:31 UTC, merged