Submit circuit batch
iqm-finland/iqm-client pull request #34
Opened 2022-06-14 09:20 UTC by hay-k

2022-06-27 07:32 UTC, ollityrkko requested changes

2022-06-27 07:32 UTC, ollityrkko commented on src/iqm_client/iqm_client.py
>              qubit_mapping: Mapping of human-readable (logical) qubit names in ``circuit`` to physical qubit names.
``circuit`` -> ``circuits``

Should there also be a clarification that even if ``qubit_mapping`` is a list, it is shared by all circuit in ``circuits``, i.e. the first item is not just for the first circuit but all items apply to all circuits?

2022-06-27 07:32 UTC, ollityrkko commented on src/iqm_client/iqm_client.py
>              shots: number of times ``circuit`` is executed
``circuit`` -> each circuit in in the batch

2022-06-27 07:32 UTC, ollityrkko commented on src/iqm_client/iqm_client.py
> +    'batch of quantum circuit(s) to execute'
It should be mentioned in the documentation that each circuit must measure same qubits.

2022-06-27 07:32 UTC, ollityrkko commented on src/iqm_client/iqm_client.py
> +    'if the run has finished successfully, the measurement results for the circuit(s)'
I suppose the whole batch either succeeds or fails, so there is no need for individual status for each circuit?

2022-06-27 07:32 UTC, ollityrkko commented on src/iqm_client/iqm_client.py
>      shots: int = Field(..., description='how many times to execute the circuit')
the circuit -> each circuit in the batch

2022-06-27 12:52 UTC, smite commented on src/iqm_client/iqm_client.py
> +"""Type to represent measurement results from a single circuit. Maps measurement keys to corresponding results."""
```suggestion
"""Measurement results from a single circuit. For each measurement operation in the circuit, maps the measurement key to the corresponding results. The outer list elements correspond to shots, and the inner list elements to the qubits measured in the measurement operation."""
```

2022-06-27 13:17 UTC, q-mat-beu commented on src/iqm_client/iqm_client.py
> +    'if the run has finished successfully, the measurement results for the circuit(s)'
I think the idea here was that you can submit a single circuit or multiple circuits by having a list of length 1 or > 1. I guess the parentheses is meant to be grammatically correct for both cases.

2022-06-27 13:24 UTC, q-mat-beu commented on src/iqm_client/iqm_client.py
>              qubit_mapping: Mapping of human-readable (logical) qubit names in ``circuit`` to physical qubit names.
Added a note to the docstring. If we want to make it more clear we could define a type `QubitMapping = list[SingleQubitMapping]`. `list[SingleQubitMapping]` is actually not multiple `qubit_mappings` but a list of `single_qubit_mappings` that are then transformed in one `qubit_mapping`. I don't know why we have this list instead of a JSON, but that is the way it is.

2022-06-27 13:24 UTC, q-mat-beu commented on src/iqm_client/iqm_client.py
>              shots: number of times ``circuit`` is executed
Applied the change.

2022-06-27 13:37 UTC, q-mat-beu commented on src/iqm_client/iqm_client.py
> +    'batch of quantum circuit(s) to execute'
Applied the change

2022-06-28 06:59 UTC, ollityrkko commented on src/iqm_client/iqm_client.py
> +    'if the run has finished successfully, the measurement results for the circuit(s)'
My comment was intended more as a question and referred to ``status`` field of RunResult. I suppose there is no need to expand that to a list.

2022-06-28 07:02 UTC, q-mat-beu commented on src/iqm_client/iqm_client.py
> +    'if the run has finished successfully, the measurement results for the circuit(s)'
Ah, ok. Yes there will be only one status for a batch execution `RunResult`.

2022-06-28 07:06 UTC, ollityrkko approved these changes

2022-06-28 07:11 UTC, merged