Add optional calibration_set_id to the request sent to IQM Server
iqm-finland/iqm-client pull request #40
Opened 2022-08-15 07:22 UTC by freetonik

Allow users to provide a `calibration_set_id`. Calibration data will be retrieved from the observations database by IQM Server. If `calibration_set_id` is provided, `settings` should not be provided, and vice versa (IQM Server, namely CoCoS, will reject any requests containing both fields simultaneously).

2022-08-15 19:01 UTC, smite requested changes

2022-08-16 07:02 UTC, hay-k commented on src/iqm_client/iqm_client.py
> +        description='EXA settings node containing the calibration data, or None to use the latest calibration set'
```suggestion
        description='IQM hardware settings and calibration data, or None to use the latest calibration set'
```

2022-08-16 07:03 UTC, hay-k commented on src/iqm_client/iqm_client.py
> +    'EXA settings node containing the calibration data, or None to use the latest calibration set'
Same here.

2022-08-16 07:17 UTC, freetonik commented on src/iqm_client/iqm_client.py
> +        description='EXA settings node containing the calibration data, or None to use the latest calibration set'
Good call, done.

2022-08-16 07:25 UTC, ollityrkko approved these changes

2022-08-16 09:02 UTC, smite approved these changes

2022-08-16 09:10 UTC, merged