Add basic HTTP auth.
iqm-finland/iqm-client pull request #9
Opened 2021-11-22 10:04 UTC by manevala

2021-11-22 14:24 UTC, olliahonen commented on src/iqm_client/iqm_client.py
> +        username: username, if required by the IQM Cortex server. This can also be set in the IQM_SERVER_USERNAME
```suggestion
        username: username, if required by the IQM server. This can also be set in the IQM_SERVER_USERNAME
```

2021-11-22 14:25 UTC, olliahonen commented on src/iqm_client/iqm_client.py
> +        username: username, if required by the IQM Cortex server. This can also be set in the IQM_SERVER_USERNAME
I don't think Cortex is mentioned in any of the public documentation (yet) :)

2021-11-22 14:25 UTC, olliahonen commented on src/iqm_client/iqm_client.py
> +        api_key: API key, if required by the IQM Cortex server. This can also be set in the IQM_SERVER_API_KEY
```suggestion
        api_key: API key, if required by the IQM server. This can also be set in the IQM_SERVER_API_KEY
```

2021-11-22 14:37 UTC, hay-k commented on src/iqm_client/iqm_client.py
> +    key = api_key if api_key else os.environ.get('IQM_SERVER_API_KEY')
```suggestion
    uname = username or os.environ.get('IQM_SERVER_USERNAME')
    key = api_key or os.environ.get('IQM_SERVER_API_KEY')
```

2021-11-23 11:46 UTC, hay-k approved these changes

2021-11-23 11:52 UTC, merged

2021-11-23 12:00 UTC, smite requested changes